name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Compile resume
        uses: xu-cheng/latex-action@v2
        with:
          root_file: cv_rian_koja.tex
      - name: Move PDF
        run: |
          mkdir build
          mv cv_rian_koja.pdf 'build/cv_rian_koja.pdf'
      - name: Push build
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build
          FOLDER: build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
